# Generated by Django 6.0.7 on 2026-07-28 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rejections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CAPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('root_cause', models.TextField()),
                ('corrective_action', models.TextField()),
                ('preventive_action', models.TextField()),
                ('target_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue')], default='OPEN', max_length=20)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_capas', to=settings.AUTH_USER_MODEL)),
                ('rejection_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capa', to='rejections.rejectionentry')),
            ],
            options={
                'verbose_name': 'CAPA',
                'verbose_name_plural': 'CAPA',
                'db_table': 'capa',
                'ordering': ['-created_at'],
            },
        ),
    ]
