# Generated by Django 6.0.7 on 2026-07-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capa',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='capa_reports/'),
        ),
    ]
