# Generated by Django 6.0.7 on 2026-07-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capa', '0003_capa_approval_status_capa_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capa',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUPERVISOR_APPROVED', 'Supervisor Approved'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
