# Generated by Django 6.0.7 on 2026-07-28 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rejections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_level', models.CharField(choices=[('SUPERVISOR', 'Supervisor'), ('HOD', 'HOD'), ('QUALITY_HEAD', 'Quality Head'), ('PLANT_HEAD', 'Plant Head')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to=settings.AUTH_USER_MODEL)),
                ('rejection_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='rejections.rejectionentry')),
            ],
            options={
                'db_table': 'approvals',
                'ordering': ['created_at'],
            },
        ),
    ]
