# Generated by Django 6.0.7 on 2026-07-28 07:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('defect_code', models.CharField(max_length=20, unique=True)),
                ('defect_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Defect Type',
                'verbose_name_plural': 'Defect Types',
                'db_table': 'defect_types',
                'ordering': ['defect_name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department_code', models.CharField(max_length=20, unique=True)),
                ('department_name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
                'ordering': ['department_name'],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_code', models.CharField(max_length=20, unique=True)),
                ('operation_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Operation',
                'verbose_name_plural': 'Operations',
                'db_table': 'operations',
                'ordering': ['operation_name'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part_number', models.CharField(max_length=50, unique=True)),
                ('part_name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Part',
                'verbose_name_plural': 'Parts',
                'db_table': 'parts',
                'ordering': ['part_number'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift_code', models.CharField(max_length=20, unique=True)),
                ('shift_name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
                'db_table': 'shifts',
                'ordering': ['shift_code'],
            },
        ),
        migrations.CreateModel(
            name='RejectionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slip_number', models.CharField(max_length=30, unique=True)),
                ('entry_date', models.DateField()),
                ('produced_quantity', models.PositiveIntegerField()),
                ('rejected_quantity', models.PositiveIntegerField()),
                ('rejection_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_APPROVAL', 'In Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_rejection_entries', to=settings.AUTH_USER_MODEL)),
                ('defect_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rejection_entries', to='rejections.defecttype')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rejection_entries', to='rejections.department')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rejection_entries', to='rejections.operation')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rejection_entries', to='rejections.part')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rejection_entries', to='rejections.shift')),
            ],
            options={
                'verbose_name': 'Rejection Entry',
                'verbose_name_plural': 'Rejection Entries',
                'db_table': 'rejection_entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
