# Generated by Django 6.0.7 on 2026-07-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rejectionentry',
            name='part',
        ),
        migrations.RemoveField(
            model_name='rejectionentry',
            name='shift',
        ),
        migrations.AddField(
            model_name='rejectionentry',
            name='part_number',
            field=models.CharField(default='UNKNOWN', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rejectionentry',
            name='operation',
            field=models.CharField(max_length=150),
        ),
    ]
