# Generated by Django 6.0.7 on 2026-07-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejections', '0002_remove_rejectionentry_part_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejectionentry',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_SUPERVISOR', 'Pending Supervisor'), ('PENDING_HOD', 'Pending HOD'), ('PENDING_QUALITY_HEAD', 'Pending Quality Head'), ('PENDING_PLANT_HEAD', 'Pending Plant Head'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20),
        ),
    ]
