# Generated by Django 6.0.7 on 2026-07-30 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='capa_submission_days',
        ),
    ]
