# Generated by Django 6.0.7 on 2026-07-28 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rejections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoresMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('movement_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Received'), ('RETURNED', 'Returned'), ('SCRAPPED', 'Scrapped')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stores_movements', to=settings.AUTH_USER_MODEL)),
                ('rejection_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stores_movement', to='rejections.rejectionentry')),
            ],
            options={
                'verbose_name': 'Stores Movement',
                'verbose_name_plural': 'Stores Movements',
                'db_table': 'stores_movements',
                'ordering': ['-movement_date'],
            },
        ),
    ]
